apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        # Аннотации для Prometheus scrape (без Operator)
        prometheus.io/scrape: "true"
        prometheus.io/port:   "5000"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: DB_HOST
              value: postgres.todo-dev.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: todoapp
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: REDIS_HOST
              value: redis.todo-dev.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: PORT
              value: "5000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.observability.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: todo-backend
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu:    100m
              memory: 128Mi
            limits:
              cpu:    500m
              memory: 512Mi
