apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - ../../base

patches:
  - path: postgres-patch.yaml
  - path: redis-patch.yaml

secretGenerator:
- name: postgres-secret
  literals:
  - username=devuser
  - password=devpass123
generatorOptions:
  disableNameSuffixHash: true
